version: "3.9"

services:
  db:
    image: postgres:16
    container_name: editor-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: editor-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build:
      context: ./editor-back
      dockerfile: Dockerfile
    container_name: editor-back
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./editor-front
    container_name: editor-front
    depends_on:
      - backend
    ports:
      - "3000:80"
    # если фронт обращается к беку:
    # REACT/VITE_BASE_URL=http://localhost:8080 или http://backend:8080

volumes:
  pgdata:
